<?php

use Phinx\Migration\AbstractMigration;

class InitialMigration extends AbstractMigration
{
    public function up() {
        $this->execute(
            'CREATE TABLE users (
                id INT AUTOGENERATED
            )'
        );
    }

    public function down() {
        $this->execute(
            'DROP TABLE users'
        );
    }
}
